# Luksemburg (bazylia)
# loop:
# Kiszyniów (oregano)
# San Marino
# :endloop
# 8 945 665

game:
  turnsAmount: 60
  startGold: 100
world:
  xSize: 20
  ySize: 10
  cities:
  - name: Luksemburg
    position:
      x: 6
      y: 7
    goods:
    - name: bazylia
      price: 16
    - name: oregano
      price: 64
    - name: tymianek
      price: 19
  - name: San Marino
    position:
      x: 20
      y: 10
    goods:
    - name: bazylia
      price: 71
    - name: oregano
      price: 96
    - name: tymianek
      price: 64
  - name: Kiszyniów
    position:
      x: 16
      y: 4
    goods:
    - name: bazylia
      price: 45
    - name: oregano
      price: 3
    - name: tymianek
      price: 37
ai:
  traders:
    - name: pacynka
      strategy:
        name: AIPuppetStrategy
        script: pacynka
    - name: AITrader0
    - name: AITrader1
    - name: AITrader2