# loop(3):
# Astana (bazylia)
# Skopje (tymianek)
# :endloop
# Astana (bazylia)
# Zagrzeb
# 2 129 424 668

game:
  turnsAmount: 60
  startGold: 100
world:
  xSize: 20
  ySize: 10
  startGold: 100
  cities:
  - name: Astana
    position:
      x: 10
      y: 7
    goods:
    - name: bazylia
      price: 17
    - name: oregano
      price: 76
    - name: tymianek
      price: 98
  - name: Skopje
    position:
      x: 17
      y: 8
    goods:
    - name: bazylia
      price: 98
    - name: oregano
      price: 58
    - name: tymianek
      price: 10
  - name: Zagrzeb
    position:
      x: 10
      y: 4
    goods:
    - name: bazylia
      price: 41
    - name: oregano
      price: 46
    - name: tymianek
      price: 88
ai:
  traders:
    - name: spryciarz
      strategy: 
        name: AIPuppetStrategy
        script: spryciarz
    - name: normal
      strategy: 
        name: AIPuppetStrategy
        script: normal
    - name: AITrader0
    - name: AITrader1
    - name: AITrader2
