# loop:
# Ryga (bazylia)
# Lizbona (tymianek)
# Praga (oregano)
# :endloop
# 9 339 848 526 672

game:
  turnsAmount: 120
  startGold: 100
world:
  xSize: 20
  ySize: 10
  cities:
  - name: Ryga
    position:
      x: 16
      y: 5
    goods:
    - name: bazylia
      price: 9
    - name: oregano
      price: 43
    - name: tymianek
      price: 49
  - name: Praga
    position:
      x: 8
      y: 1
    goods:
    - name: bazylia
      price: 21
    - name: oregano
      price: 3
    - name: tymianek
      price: 58
  - name: Lizbona
    position:
      x: 2
      y: 5
    goods:
    - name: bazylia
      price: 66
    - name: oregano
      price: 41
    - name: tymianek
      price: 11
ai:
  traders:
    - name: pacynka
      strategy:
        name: AIPuppetStrategy
        script: pacynka
    - name: AITrader0
    - name: AITrader1
    - name: AITrader2