# loop:
# Vaduz (bazylia)
# Skopje (tymianek)
# Tallin (oregano)
# :endloop
# 2 578 760 694

# wyświetlanie highscore w main menu
# logowanie ruchów AI

# zaprogramowany AI, jeździ wg zaplanowanej trasy i kupuje co ma kupować. język:
# miasto1 (coTamKupić)
# loop(3):
# miasto2 (coTamKupić)
# miasto3 (coTamKupić)
# :endloop

# potrzebuję takiej trasy, że A -> B -> C -> A i z jednego musisz jeździć na pusto
# znajdywacz najlepszej trasy

world:
  xSize: 10
  ySize: 10
  startGold: 100
  turnsAmount: 60
  cities:
  - name: Tallin
    position:
      x: 3
      y: 9
    goods:
    - name: bazylia
      price: 89
    - name: oregano
      price: 11
    - name: tymianek
      price: 81
  - name: Skopje
    position:
      x: 7
      y: 10
    goods:
    - name: bazylia
      price: 94
    - name: oregano
      price: 53
    - name: tymianek
      price: 56
  - name: Vaduz
    position:
      x: 2
      y: 4
    goods:
    - name: bazylia
      price: 3
    - name: oregano
      price: 45
    - name: tymianek
      price: 55
